blueprint:
  name: Customizable Door/Window Open Alert
  description: >-
    Sends a configurable notification if a door or window is left open for a
    specific duration. Features customizable text, button titles, and time delays.
  domain: automation
  source_url: https://gist.githubusercontent.com/DestynnReigneer/81fd6c3ca1993f5068678c56fc5c0671/raw/55eeeb13e74f02ebe1d6641ecce9c543f4467b6e/open_alert_customizable.yaml

  input:
    sensor_to_monitor:
      name: Sensor to Monitor
      description: The sensor entity to monitor (e.g., door, window, garage).
      selector:
        entity:
          domain: binary_sensor
          multiple: false

    initial_trigger_time_minutes:
      name: Initial Alert Time (minutes)
      description: The number of minutes the sensor must be on before the first alert is sent.
      selector:
        number:
          min: 1
          max: 120
          unit_of_measurement: "minutes"
          mode: box
          
    notification_devices:
      name: Notification Devices
      description: The devices that will receive the alert notification.
      selector:
        device:
          domain: mobile_app
          multiple: true
          
    closable_device:
      name: Closable Device (Optional)
      description: >-
        The entity that can close the door/window (e.g., a cover or switch). If
        left empty, the 'open app' option will be shown instead.
      selector:
        entity:
          domain: cover
          multiple: false

    initial_notification_message:
      name: Initial Notification Message
      description: The message for the first notification.
      selector:
        text:
          multiline: true

    # Button titles and delays
    option_1_title:
      name: Option 1 Button Title
      description: The text for the first button option.
      selector:
        text:
          multiline: false
          
    option_1_delay_minutes:
      name: Option 1 Delay (minutes)
      description: The number of minutes to wait before re-sending the alert.
      selector:
        number:
          min: 1
          max: 120
          unit_of_measurement: "minutes"
          mode: box

    option_2_title_closable:
      name: Option 2 Title (If Closable Device Is Set)
      description: The text for the second button if a closable device is configured.
      selector:
        text:
          multiline: false

    option_2_title_non_closable:
      name: Option 2 Title (If No Device)
      description: The text for the second button if no closable device is configured.
      selector:
        text:
          multiline: false

    option_3_title:
      name: Option 3 Button Title
      description: The text for the third button option.
      selector:
        text:
          multiline: false
          
    option_3_delay_minutes:
      name: Option 3 Delay (minutes)
      description: The number of minutes to wait before re-sending the alert.
      selector:
        number:
          min: 1
          max: 120
          unit_of_measurement: "minutes"
          mode: box

    # Custom messages for the "Acknowledge & Close" path
    acknowledgment_message_text:
      name: Acknowledgment Message
      description: >-
        The message sent after selecting the acknowledge option. Use '{person}' to
        show the device name.
      selector:
        text:
          multiline: true
          
    acknowledgment_check_delay_minutes:
      name: Acknowledgment Check Delay (minutes)
      description: The time to wait after acknowledgment before re-checking the sensor.
      selector:
        number:
          min: 1
          max: 120
          unit_of_measurement: "minutes"
          mode: box
          
    urgent_prefix_text:
      name: Urgent Prefix Text
      description: The prefix for the re-sent notification after an urgent check fails.
      selector:
        text:
          multiline: false

    # Custom messages for the "Close" path
    confirmation_message_text:
      name: Confirmation Message
      description: The message sent to confirm the device has been closed.
      selector:
        text:
          multiline: true
          
    failure_message_text:
      name: Closing Failure Message
      description: >-
        The message sent if the device was told to close but the sensor is still
        on.
      selector:
        text:
          multiline: true
          
mode: queued

trigger:
  - platform: state
    entity_id: !input sensor_to_monitor
    to: 'on'
    for:
      minutes: !input initial_trigger_time_minutes

variables:
  notification_id: alert_{{ trigger.entity_id.split('.')[1] }}_{{ now().timestamp() | int }}

action:
  # The main action block to send the initial notification.
  - service: notify.mobile_app
    data:
      title: "Alert"
      message: !input initial_notification_message
      data:
        actions:
          - action: "wait_1"
            title: !input option_1_title
          - action: "close"
            title: >-
              {% if is_device_id(input('closable_device')) %}
                {{ input('option_2_title_closable') }}
              {% else %}
                {{ input('option_2_title_non_closable') }}
              {% endif %}
          - action: "wait_2"
            title: !input option_3_title
        tag: !input notification_id

  # Wait for a user response
  - wait_for_trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: "wait_1"
          tag: !input notification_id
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: "close"
          tag: !input notification_id
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: "wait_2"
          tag: !input notification_id

  - choose:
      # --- Option 1: Wait 1
      - conditions: "{{ wait.trigger.event.data.action == 'wait_1' }}"
        sequence:
          - service: mobile_app
            data:
              action: "dismiss_notification"
              data:
                tag: !input notification_id
          - delay:
              minutes: !input option_1_delay_minutes
          - repeat:
              until: "{{ states(input('sensor_to_monitor')) == 'off' }}"
              sequence:
                - service: notify.mobile_app
                  data:
                    title: "Alert"
                    message: !input initial_notification_message
                    data:
                      actions:
                        - action: "wait_1"
                          title: !input option_1_title
                        - action: "close"
                          title: >-
                            {% if is_device_id(input('closable_device')) %}
                              {{ input('option_2_title_closable') }}
                            {% else %}
                              {{ input('option_2_title_non_closable') }}
                            {% endif %}
                        - action: "wait_2"
                          title: !input option_3_title
                      tag: !input notification_id
                - delay:
                    minutes: !input option_1_delay_minutes

      # --- Option 2: Close
      - conditions: "{{ wait.trigger.event.data.action == 'close' }}"
        sequence:
          - variables:
              device_name: >-
                {{ device_attr(wait.trigger.event.data.device_id, 'name') }}
          - choose:
              # Scenario 2a: No Closable Device configured
              - conditions: "{{ not is_device_id(input('closable_device')) }}"
                sequence:
                  - service: notify.mobile_app
                    data:
                      message: "{{ input('acknowledgment_message_text') | replace('{person}', device_name) }}"
                      data:
                        tag: !input notification_id
                  - delay:
                      minutes: !input acknowledgment_check_delay_minutes
                  - repeat:
                      until: "{{ states(input('sensor_to_monitor')) == 'off' }}"
                      sequence:
                        - service: notify.mobile_app
                          data:
                            title: !input urgent_prefix_text
                            message: !input initial_notification_message
                            data:
                              actions:
                                - action: "wait_1"
                                  title: !input option_1_title
                                - action: "close"
                                  title: >-
                                    {% if is_device_id(input('closable_device')) %}
                                      {{ input('option_2_title_closable') }}
                                    {% else %}
                                      {{ input('option_2_title_non_closable') }}
                                    {% endif %}
                                - action: "wait_2"
                                  title: !input option_3_title
                              tag: !input notification_id
                        - delay:
                            minutes: 5 # A short delay to avoid spamming.

              # Scenario 2b: Closable Device IS configured
              - conditions: "{{ is_device_id(input('closable_device')) }}"
                sequence:
                  - service: cover.close_cover
                    entity_id: !input closable_device
                  - service: notify.mobile_app
                    data:
                      title: "Alert"
                      message: !input confirmation_message_text
                      data:
                        tag: !input notification_id
                  - delay:
                      minutes: 1
                  - repeat:
                      until: "{{ states(input('sensor_to_monitor')) == 'off' }}"
                      sequence:
                        - service: notify.mobile_app
                          data:
                            title: "Alert"
                            message: !input failure_message_text
                            data:
                              tag: !input notification_id
                        - delay:
                            minutes: 5

      # --- Option 3: Wait 2
      - conditions: "{{ wait.trigger.event.data.action == 'wait_2' }}"
        sequence:
          - service: mobile_app
            data:
              action: "dismiss_notification"
              data:
                tag: !input notification_id
          - delay:
              minutes: !input option_3_delay_minutes
          - repeat:
              until: "{{ states(input('sensor_to_monitor')) == 'off' }}"
              sequence:
                - service: notify.mobile_app
                  data:
                    title: "Alert"
                    message: !input initial_notification_message
                    data:
                      actions:
                        - action: "wait_1"
                          title: !input option_1_title
                        - action: "close"
                          title: >-
                            {% if is_device_id(input('closable_device')) %}
                              {{ input('option_2_title_closable') }}
                            {% else %}
                              {{ input('option_2_title_non_closable') }}
                            {% endif %}
                        - action: "wait_2"
                          title: !input option_3_title
                      tag: !input notification_id
                - delay:
                    minutes: !input option_3_delay_minutes
